$(document).ready(function(){
	$('#boi-loks').click(function(e){
		e.preventDefault();
		$('#boi-lok').show();
	});
	$('#boi-udds').click(function(e){
		e.preventDefault();
		$('#boi-udd').show();
	});
	$('#tap-loks').click(function(e){
		e.preventDefault();
		$('#tap-lok').show();
	});
	$('#tap-udds').click(function(e){
		e.preventDefault();
		$('#tap-udd').show();
	});
	$('#prob-loks').click(function(e){
		e.preventDefault();
		$('#prob-lok').show();
	});
	$('#prob-udds').click(function(e){
		e.preventDefault();
		$('#prob-udd').show();
	});
	$('#alok-loks').click(function(e){
		e.preventDefault();
		$('#alok-lok').show();
	});
	$('#alok-udds').click(function(e){
		e.preventDefault();
		$('#alok-udd').show();
	});
});